name: Flutter Building Release

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  android:
    runs-on: ubuntu-latest
    env:
      output: "${{ github.workspace }}/build/app/outputs/apk/release"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Java JDK Build Action
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle Build Action
        uses: gradle/gradle-build-action@v3.1.0

      - name: Flutter action
        uses: subosito/flutter-action@v2.9.1
        with:
          flutter-version: '3.16.2'
          channel: 'stable'

      #- name: Analyze project source
       # run: flutter analyze

      - name: Install dependencies
        run: dart pub get

      - name: Install dependencies
        run: dart pub outdated

      - name: Flutter build apk
        run: flutter build apk --obfuscate --split-debug-info=test/ --no-tree-shake-icons --split-per-abi --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path:  ${{ env.output }}/*-v8a-release.apk
